[tool.poetry]
name = "webserial-scraper"
version = "1.0.0"
description = ""
authors = ["Curetix <curetix@pm.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "webserial_scraper"}]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.11.2"
click = "^8.1.3"
platformdirs = "^3.0.0"
EbookLib = "^0.18"
python-box = {extras = ["all"], version = "^7.0.0"}
questionary = "^1.10.0"
requests = "^2.28.2"
schema = "^0.7.5"
prompt-toolkit = "^3.0.36"
fire = "^0.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
