[tool.poetry]
name = "webserial-scraper"
version = "1.0.0"
description = ""
authors = ["Curetix <curetix@pm.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "webserial_scraper"}]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.12.3"
click = "^8.1.7"
platformdirs = "^3.11.0"
EbookLib = "^0.18"
python-box = {extras = ["all"], version = "^7.1.1"}
questionary = "^2.0.1"
requests = "^2.31.0"
schema = "^0.7.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
