start_url: https://www.royalroad.com/fiction/26675/a-journey-of-black-and-red/chapter/393832/1-cruel-genesis
metadata:
  title: A Journey of Black and Red
  author: Mecanimus
  description: |
    Where am I? What is this! I... I don't remember anything. I am in chains? Why am I in chains?! And why am I so very...
    Thirsty.

    This is a story of vampires as I believe they should be, with their strengths and weaknesses,
    with their remnants of humanity and the beast inside.
files:
  cover_file: https://www.royalroadcdn.com/public/covers-large/26675-a-journey-of-black-and-red.jpg
selectors:
  content_element: .chapter-content
  next_chapter_element: .nav-buttons a:-soup-contains("Next Chapter")
  title_element: .fic-header h1
substitutions:
  - chapterUrl: https://www.royalroad.com/fiction/26675/a-journey-of-black-and-red/chapter/426349/34-ring-breaker
    selectorType: text
    selector: </p> <p>
    replaceWith: </p><p>