start_url: https://www.royalroad.com/fiction/41033/kairos-a-greek-myth-litrpg/chapter/642057/1-the-legend-of-kairos
end_url: https://www.royalroad.com/fiction/41033/kairos-a-greek-myth-litrpg/chapter/892504/the-legend-of-kairos-epilogue
metadata:
  title: Kairos
  author: Maxime J. Durand (Void Herald)
  description: |
    It has been centuries since mortals unlocked the secrets of the Fate System and overthrew Mount Olympus. The old gods are dead, and their thrones are empty. Kairos, a young pirate with the ability to speak with animals, has an ambition: to ascend as the newest deity of a flooded world. But divine power is not given. It is taken.

    Now Kairos must sail the endless sea, tame fearsome monsters, and conquer new lands. The challenges are many, but he will face them all. For Kairos is a cunning [Rogue] indeed...
files:
  cover_file: https://www.royalroadcdn.com/public/covers-large/kairos-a-greek-myth-litrpg-aacaznppuw8.jpg
style: |
  table {
      background: #004b7a;
      margin: 10px auto;
      border: none;
      box-shadow: 1px 1px 1px rgb(0 0 0 / 75%)
      border-spacing: 2px;
  }
  table td {
      margin: 3px;
      padding: 5px;
      color: #ccc;
      border: 1px solid hsla(0,0%,100%,.25)!important;
      background: rgba(0,0,0,.1);
  }
selectors:
  content_element: .chapter-content
  next_chapter_element: .nav-buttons a:-soup-contains("Next Chapter")
  title_element: .fic-header h1
skip_conversion: true