# The Wandering Inn - Volume 8
# by pirateaba
# https://wanderinginn.com

#####################################################################

startUrl: https://wanderinginn.com/2021/01/10/8-00/

crawlerModule: WanderingInnPatreonCrawler

metadata:
  title: The Wandering Inn - Volume 8
  author: pirateaba
  description: |
    "No killing Goblins."

    So reads the sign outside of the Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.

    It's a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a dragon. She doesn't belong in a place where monster attacks are a fact of life, and where humans are one species among many. But she must adapt to her new life. Or die.

    In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no [Warrior], no [Mage]. Erin Solstice runs an inn.

    She's an [Innkeeper].

selectors:
  titleElement: .entry-title
  contentElement: .entry-content
  nextChapterElement: .entry-content a:-soup-contains("Next Chapter")
  cutOffElement:
    - p:-soup-contains("After Chapter Thoughts:")
    - p:-soup-contains("After Chapter Notes:")
    - p:-soup-contains("Author’s Note:")
    - p:-soup-contains("Author’s Notes:")
    - p:has(a:-soup-contains("Previous Chapter"))
    - p:has(a:-soup-contains("Next Chapter"))

substitutions:
  - selectorType: text
    selector: <p>—-</p>
    replaceWith: <hr/>
  - selectorType: text
    selector: <p>—–</p>
    replaceWith: <hr/>
  - chapterUrl: https://wanderinginn.com/2021/01/10/8-00/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/01/13/8-01/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/01/27/8-04-t/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/02/07/8-05-i/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/02/10/8-06-rt/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/02/14/8-07-l/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/02/17/8-08-j/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/02/21/8-09/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/02/24/8-10/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/02/24/8-10/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/03/07/8-11-e/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/03/14/interlude-the-rower-and-the-bartender/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2021/03/17/8-13-f/
    selectorType: css
    selector: p:-soup-contains("On Sunday, 6 PM EST, Rebecca Brewer")
  - chapterUrl: https://wanderinginn.com/2021/03/21/8-14-n/
    selectorType: css
    selector: p:-soup-contains("The author is on break")
  - chapterUrl: https://wanderinginn.com/2021/03/21/8-14-n/
    selectorType: css
    selector: p:-soup-contains("Rebecca Brewer, the editor who worked on 8.11 E")
  - chapterUrl: https://wanderinginn.com/2021/03/21/8-14-n/
    selectorType: css
    selector: p:-soup-contains("Also, she has done an interview with The Fantasy Inn!")
  - chapterUrl: https://wanderinginn.com/2021/03/30/8-15/
    selectorType: css
    selector: p:-soup-contains("Iron Prince by Bryce O’Conner")
  - chapterUrl: https://wanderinginn.com/2021/04/04/interlude-paradigm-shift-pt-1/
    selectorType: css
    selector: p:-soup-contains("Enuryn the [Naturalist] has opened an online store")
  - chapterUrl: https://wanderinginn.com/2021/04/04/interlude-paradigm-shift-pt-2/
    selectorType: css
    selector: p:-soup-contains("I am skipping the next update and will be posting the next chapter on the 10th")
  - chapterUrl: https://wanderinginn.com/2021/04/10/8-16/
    selectorType: css
    selector: p:-soup-contains("Podium Publishing is offering a TWI-embossed frying pan giveaway")
  - chapterUrl: https://wanderinginn.com/2021/04/13/8-17-h/
    selectorType: css
    selector: p:-soup-contains("Podium Publishing is offering a TWI-embossed frying pan giveaway")
  - chapterUrl: https://wanderinginn.com/2021/04/13/8-17-h/
    selectorType: css
    selector: p:-soup-contains("Also, I am taking my break early due to getting the vaccine shot")