# This is an example of an absolute minimum config file Volume 1 of 'The Wandering Inn' by pirateaba
# https://wanderinginn.com

#####################################################################

# URL of the first chapter (or prologue) of the webfiction
startUrl: https://www.royalroad.com/fiction/10073/the-wandering-inn/chapter/113220/100
endUrl: https://www.royalroad.com/fiction/10073/the-wandering-inn/chapter/122274/145

# EPUB metadata
metadata:
  title: The Wandering Inn - Volume 1
  author: pirateaba

# Element selectors. You can use both CSS and XPATH selectors. For more information see the Scrapy Selectors documentation.
selectors:
  titleElement: h1
  contentElement: .chapter-content
  nextChapterElement: .nav-buttons .col-lg-offset-6 a